version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.7.17"

sphinx:
  configuration: docs/conf.py

formats: []

python:
  # version: 3.7 # This setting is not in the official docs for readthedocs
  install:
    - requirements: docs/requirements.txt
