name: Run Unit Tests via Pytest  
  
on: [push]

jobs:  
  build:  
    runs-on: self-hosted
    strategy:  
      matrix:  
        python-version: ["3.7"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python3 -m pip install --upgrade pip
          pip3 install malaya tensorflow tensorflow-text
          pip3 install pytest pytest-cov pytest-codecov gitpython
      - name: Test with pytest  
        run: |  
          pytest tests --cov --cov-report term --cov-report html
